"""add_super_user

Revision ID: 9ae08a57a3ac
Revises: ef4113a01fca
Create Date: 2023-12-17 00:53:49.277027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae08a57a3ac'
down_revision = 'ef4113a01fca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isSuperUser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isSuperUser')
    # ### end Alembic commands ###
