"""update_user_table

Revision ID: ef4113a01fca
Revises: b9724bb9e773
Create Date: 2023-12-14 00:24:41.440938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4113a01fca'
down_revision = 'b9724bb9e773'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_links')
    op.add_column('users', sa.Column('user_department', sa.String(), nullable=True))
    op.add_column('users', sa.Column('user_birthdate', sa.DateTime(), nullable=True))
    op.drop_column('users', 'user_status')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'user_avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('user_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'user_birthdate')
    op.drop_column('users', 'user_department')
    op.create_table('user_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='user_links_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_links_pkey')
    )
    # ### end Alembic commands ###
